apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-reader
  labels:
    app: file-reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-reader
  template:
    metadata:
      labels:
        app: file-reader
    spec:
      containers:
      - name: file-reader
        image: docker.io/library/file-reader:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: data-mount
        env:
          - name: PARSER_URL
            value: "http://parser-svc.default.svc.cluster.local/parse"
      volumes:
        - name: data-mount
          hostPath:
            path: /data
---
apiVersion: v1
kind: Service
metadata:
  name: file-reader-svc
spec:
  selector:
    app: file-reader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
