apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-loader
  labels:
    app: file-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-loader
  template:
    metadata:
      labels:
        app: file-loader
    spec:
      containers:
      - name: file-loader
        image: file-loader
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: file-loader-svc
spec:
  selector:
    app: file-loader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
