apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      containers:
      - name: collector
        image: collector
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: collector-svc
spec:
  selector:
    app: collector
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

